Controllers for GET
SyedMa3/SAC-website pull request #5
Opened 2024-02-14 15:32 UTC by nnk03

Pull request for #2

2024-02-16 15:28 UTC, SyedMa3 requested changes

2024-02-16 15:28 UTC, SyedMa3 commented on src/backend/controllers/controllers.js
Define just the functions that will be called by the routes team.

Also use, `express-async-handler`.
Also, different file for different model. Like announcements.controllers.js

2024-02-16 15:28 UTC, SyedMa3 commented on src/backend/controllers/controllers.js
Also, contact models team to get to know about the models they defined.

2024-02-18 07:15 UTC, SyedMa3 requested changes

2024-02-18 07:15 UTC, SyedMa3 commented on src/backend/controllers/announcements.controllers.js
You don't need to use router. You just have to define the contollers (functions) and export just them.

2024-02-18 07:23 UTC, nnk03 commented
@SyedMa3 
Now, I have removed the routers and only defined the functions for announcements

2024-02-18 07:23 UTC, SyedMa3 requested changes

2024-02-18 07:23 UTC, SyedMa3 commented on src/backend/controllers/controllers.js
Delete this file if not needed

2024-02-18 07:43 UTC, SyedMa3 approved these changes

2024-02-18 07:44 UTC, merged